/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardSubtitle: typeof import('bootstrap-vue-next')['BCardSubtitle']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    CreateBookingModal: typeof import('./src/components/bookings/CreateBookingModal.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginWindow: typeof import('./src/components/LoginWindow.vue')['default']
    MainView: typeof import('./src/components/MainView.vue')['default']
    Roadmap: typeof import('./src/components/bookings/Roadmap.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
