/*
 * This file is generated by jOOQ.
 */
package org.jooq.SWT;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.SWT.tables.AccessGroups;
import org.jooq.SWT.tables.Bookings;
import org.jooq.SWT.tables.GasCards;
import org.jooq.SWT.tables.Insurances;
import org.jooq.SWT.tables.Pricing;
import org.jooq.SWT.tables.Users;
import org.jooq.SWT.tables.Vehicles;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Swt extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SWT</code>
     */
    public static final Swt SWT = new Swt();

    /**
     * The table <code>SWT.access_groups</code>.
     */
    public final AccessGroups ACCESS_GROUPS = AccessGroups.ACCESS_GROUPS;

    /**
     * The table <code>SWT.bookings</code>.
     */
    public final Bookings BOOKINGS = Bookings.BOOKINGS;

    /**
     * The table <code>SWT.gas_cards</code>.
     */
    public final GasCards GAS_CARDS = GasCards.GAS_CARDS;

    /**
     * The table <code>SWT.insurances</code>.
     */
    public final Insurances INSURANCES = Insurances.INSURANCES;

    /**
     * The table <code>SWT.pricing</code>.
     */
    public final Pricing PRICING = Pricing.PRICING;

    /**
     * The table <code>SWT.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * The table <code>SWT.vehicles</code>.
     */
    public final Vehicles VEHICLES = Vehicles.VEHICLES;

    /**
     * No further instances allowed
     */
    private Swt() {
        super("SWT", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AccessGroups.ACCESS_GROUPS,
            Bookings.BOOKINGS,
            GasCards.GAS_CARDS,
            Insurances.INSURANCES,
            Pricing.PRICING,
            Users.USERS,
            Vehicles.VEHICLES
        );
    }
}
