/*
 * This file is generated by jOOQ.
 */
package org.jooq.SWT;


import org.jooq.SWT.tables.AccessGroups;
import org.jooq.SWT.tables.Bookings;
import org.jooq.SWT.tables.GasCards;
import org.jooq.SWT.tables.Insurances;
import org.jooq.SWT.tables.Pricing;
import org.jooq.SWT.tables.Users;
import org.jooq.SWT.tables.Vehicles;


/**
 * Convenience access to all tables in SWT.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>SWT.access_groups</code>.
     */
    public static final AccessGroups ACCESS_GROUPS = AccessGroups.ACCESS_GROUPS;

    /**
     * The table <code>SWT.bookings</code>.
     */
    public static final Bookings BOOKINGS = Bookings.BOOKINGS;

    /**
     * The table <code>SWT.gas_cards</code>.
     */
    public static final GasCards GAS_CARDS = GasCards.GAS_CARDS;

    /**
     * The table <code>SWT.insurances</code>.
     */
    public static final Insurances INSURANCES = Insurances.INSURANCES;

    /**
     * The table <code>SWT.pricing</code>.
     */
    public static final Pricing PRICING = Pricing.PRICING;

    /**
     * The table <code>SWT.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>SWT.vehicles</code>.
     */
    public static final Vehicles VEHICLES = Vehicles.VEHICLES;
}
