# docker compose -f compose.yml up mariadb -d
# docker compose -f compose.yml mariadb down
#
# Compose V2

name: xy_fleet_database_environment
services:

  mariadb:
    image: mariadb:latest
    # userns_mode: keep-id  # needed for podman on macOS
    container_name: XY_Fleet
    environment:
      MYSQL_ROOT_PASSWORD: u2SG7FdmzNE4vZU3kVALCQhPYywfBH5X9raxWJ6T
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3308:3306"
    volumes:
      - ./mariadb_data:/var/lib/XYFleetSQL
    restart: always
